'use strict';
const AVERIS=(()=>{
const KEY="averis-neon-v6", VERSION="6.0.0";
const NAV=[["today","Today","⌂"],["people","People","◉"],["journeys","Journeys","↗"],["queue","Queue","≡"],["schedule","Schedule","◷"],["capacity","Capacity","▦"],["workforce","Workforce","◌"],["diagnostics","Diagnostics","⌁"],["pharmacy","Pharmacy","✚"],["finance","Finance","◇"],["messages","Messages","✉"],["incidents","Incidents","⚠"],["quality","Quality","✓"],["insights","Insights","◫"],["assistant","Assistant","✦"],["reports","Reports","▤"],["audit","Audit","◌"],["settings","Settings","⚙"]];
const ROUTES={login:["Sign in","Access","Return to your local workspace","AVERIS account access stays inside this browser."],register:["Register","Setup","Create your local workspace","Create a synthetic control-room profile stored only in this browser."],today:["Today","Command deck","What matters right now?","Decision-first view of the synthetic operating environment."],people:["People","Coordination","Who needs attention?","Person-first records with operational context."],journeys:["Journeys","Coordination","Where is work moving?","Synthetic journey stages and handoffs."],queue:["Queue","Execution","What is late or blocked?","Prioritized operational work."],schedule:["Schedule","Execution","What moves next?","Synthetic appointment flow."],capacity:["Capacity","Execution","Where is demand pressing?","Resources and utilization."],workforce:["Workforce","Execution","Who is carrying the load?","Synthetic workforce balance."],diagnostics:["Diagnostics","Execution","Which workflow changed?","Operational workflow tracking only."],pharmacy:["Pharmacy","Execution","What inventory is under pressure?","Synthetic stock and thresholds."],finance:["Finance","Execution","What is the operating picture?","Synthetic finance records."],messages:["Messages","Coordination","What needs a response?","Local communications."],incidents:["Incidents","Execution","What needs containment?","Incident lifecycle."],quality:["Quality","Assurance","Are workflows staying healthy?","Synthetic quality indicators."],insights:["Insights","Intelligence","What pattern is emerging?","Interactive operational analytics."],assistant:["Assistant","Intelligence","What can AVERIS surface?","Local deterministic assistant."],reports:["Reports","Intelligence","What should be shared?","Previewable and runnable reports."],audit:["Audit","Governance","What changed?","Local change history."],settings:["Settings","Governance","How should AVERIS behave?","Theme, profile, notifications, persistence."]};

function peopleSeed(){return[["P-1042","Aarav Mehta","North cluster","Priority 1","Today 10:30","JOURNEY-ONBOARDING"],["P-1078","Ishita Rao","Central cluster","Priority 2","Today 11:15","JOURNEY-DIAGNOSTIC"],["P-1114","Kabir Nair","East cluster","Priority 3","Today 13:00","JOURNEY-FOLLOWUP"],["P-1160","Nisha Kapoor","South cluster","Priority 2","Today 13:30","JOURNEY-PHARMACY"],["P-1208","Rohan Iyer","West cluster","Priority 1","Today 14:00","JOURNEY-ESCALATED"],["P-1267","Meera Shah","Central cluster","Priority 3","Today 15:10","JOURNEY-REVIEW"],["P-1333","Dev Malhotra","North cluster","Priority 2","Tomorrow 09:20","JOURNEY-ONBOARDING"],["P-1389","Tara Menon","South cluster","Priority 3","Tomorrow 10:00","JOURNEY-DISCHARGE"],["P-1421","Vihaan Joshi","East cluster","Priority 2","Tomorrow 10:40","JOURNEY-FOLLOWUP"],["P-1484","Ananya Das","West cluster","Priority 1","Tomorrow 11:15","JOURNEY-ESCALATED"],["P-1537","Reyansh Sethi","Central cluster","Priority 3","Tomorrow 12:10","JOURNEY-REVIEW"],["P-1598","Myra Pillai","North cluster","Priority 2","Tomorrow 13:30","JOURNEY-DIAGNOSTIC"]].map((x,i)=>({id:x[0],name:x[1],cluster:x[2],priority:x[3],slot:x[4],journey:x[5],attention:i%4===0?"Escalated":i%3===0?"Awaiting response":"Monitoring",updated:1700000000000+i,owner:["Mahi","Asha","Ravi","Maya"][i%4],contact:i%2?"Phone":"Portal",notes:"Synthetic coordination note."}));}
function seedState(){
const people=peopleSeed(),tasks=[["T-701","Confirm appointment packet","Aarav Mehta","High","Due 10:10","Blocked"],["T-702","Route diagnostics result","Ishita Rao","Medium","Due 10:45","In progress"],["T-703","Close callback loop","Kabir Nair","Medium","Due 12:30","In progress"],["T-704","Verify stock threshold","Nisha Kapoor","High","Due 13:10","Blocked"],["T-705","Review escalated handoff","Rohan Iyer","Critical","Due 09:40","Overdue"],["T-706","Prepare journey summary","Meera Shah","Low","Due 15:00","Open"],["T-707","Assign workforce cover","Dev Malhotra","Medium","Due 16:20","Open"],["T-708","Reconcile local finance item","Tara Menon","Low","Due 17:00","Open"],["T-709","Review unread message","Vihaan Joshi","Medium","Due 17:20","In progress"],["T-710","Check queue aging","Ananya Das","High","Due 18:10","Open"]].map((x,i)=>({id:x[0],title:x[1],person:x[2],priority:x[3],due:x[4],status:x[5],owner:["Mahi","Asha","Ravi","Maya"][i%4],updated:1700000000000+i}));
const appointments=Array.from({length:10},(_,i)=>({id:"A-"+(201+i),time:["09:20","10:10","10:45","11:15","12:10","13:00","13:30","14:00","15:10","16:20"][i],person:people[i%people.length].name,resource:["Atlas Room","Nova Room","Orbit Room","Echo Room"][i%4],type:["Review","Coordination","Follow-up","Diagnostic workflow"][i%4],state:i===4?"Delayed":i===7?"Moved":"Confirmed"}));
const resources=[["R-01","Atlas Room","Room","Available",62],["R-02","Nova Room","Room","Occupied",88],["R-03","Orbit Room","Room","Available",44],["R-04","Echo Room","Room","Maintenance",0],["R-05","North pod","Virtual","Available",71],["R-06","South pod","Virtual","Occupied",91]].map((x,i)=>({id:x[0],name:x[1],type:x[2],state:x[3],util:x[4],owner:"Team "+String.fromCharCode(65+i%3)}));
const workforce=[["W-01","Asha","Coordinator","Balanced",68],["W-02","Ravi","Coordinator","High load",92],["W-03","Maya","Analyst","Balanced",61],["W-04","Sanjay","Coordinator","Available",39],["W-05","Ira","Analyst","High load",86],["W-06","Kiran","Operations","Available",48]].map(x=>({id:x[0],name:x[1],role:x[2],state:x[3],load:x[4]}));
const messages=[["M-501","Asha","Action packet is ready for review.","8 min",false],["M-502","Ravi","Queue handoff moved to 12:30.","21 min",false],["M-503","Maya","Capacity note added to the North pod.","46 min",true],["M-504","System","Synthetic export completed locally.","1 h",true],["M-505","Asha","Please review the escalated journey.","2 h",false]].map(x=>({id:x[0],from:x[1],text:x[2],when:x[3],read:x[4],reply:""}));
const incidents=[["INC-31","Delayed handoff in North cluster","High","Investigating","P-1042"],["INC-32","Inventory variance on local item","Medium","Contained","P-1160"],["INC-33","Appointment collision detected","High","Open","P-1208"],["INC-34","Resource maintenance overlap","Low","Resolved","P-1333"]].map(x=>({id:x[0],title:x[1],severity:x[2],state:x[3],person:x[4],owner:"Mahi",opened:"Today 09:20",note:"Synthetic incident record. No external action is initiated."}));
const diagnostics=Array.from({length:8},(_,i)=>({id:"DX-"+(301+i),person:people[i].name,type:["Workflow result","Imaging workflow","Lab workflow","External result simulation"][i%4],state:["Received","Review","Verified","Queued"][i%4],value:["Nominal","Pending","Variance","Reference"][i%4]}));
const pharmacy=[["RX-01","Nova-01","Unit",420,180,36],["RX-02","Nova-02","Unit",95,120,22],["RX-03","Nova-03","Unit",680,300,17],["RX-04","Nova-04","Unit",74,90,12],["RX-05","Nova-05","Pack",240,210,4],["RX-06","Nova-06","Pack",36,60,31]].map(x=>({id:x[0],item:x[1],unit:x[2],qty:x[3],minimum:x[4],variance:x[5]}));
const finance=[["F-801","Operations allocation","+₹48,500","Approved","Today"],["F-802","Synthetic service cost","-₹11,800","Posted","Today"],["F-803","Capacity adjustment","-₹4,200","Pending","Yesterday"],["F-804","Training allocation","+₹18,000","Approved","Yesterday"],["F-805","Inventory variance","-₹2,600","Review","2 days ago"]].map(x=>({id:x[0],label:x[1],amount:x[2],state:x[3],date:x[4]}));
return{version:VERSION,account:{name:"Mahi",email:"mahi@averis.local",passHash:localHash("Mahi@580")},session:{authenticated:true,lastLogin:stamp()},theme:"dark",compact:false,focus:false,notifications:true,profile:{name:"Mahi",role:"Control room owner"},people,tasks,appointments,resources,workforce,messages,incidents,diagnostics,pharmacy,finance,reports:[{id:"REP-01",name:"Morning command brief",type:"Operational",state:"Ready"},{id:"REP-02",name:"Queue aging review",type:"Execution",state:"Ready"},{id:"REP-03",name:"Capacity pressure map",type:"Capacity",state:"Ready"},{id:"REP-04",name:"Synthetic quality review",type:"Quality",state:"Draft"}],audit:[{time:new Date().toISOString(),actor:"Mahi",action:"Initialized AVERIS control room",target:"Local simulation"}]};}
function load(){try{const r=localStorage.getItem(KEY);return r?JSON.parse(r):null}catch(e){localStorage.removeItem(KEY);return null}}
let state=load()||seedState(),route=parseHash()||"today",peopleQuery="",peopleSort="attention",commandItems=[],commandIndex=0;
if(!state.account)state.account={name:state.profile?.name||"Mahi",email:"mahi@averis.local",passHash:localHash("Mahi@580")};
if(!state.session)state.session={authenticated:true,lastLogin:stamp()};
if(!state.profile)state.profile={name:state.account.name||"Mahi",role:"Control room owner"};
if(!state.session.authenticated&&route!=="login"&&route!=="register")route="login";

function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function localHash(value){let h=2166136261;for(let i=0;i<String(value).length;i++){h^=String(value).charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16)}
function nextId(prefix,list){const nums=(list||[]).map(x=>String(x.id||"").match(/(\d+)$/)).filter(Boolean).map(x=>Number(x[1]));const n=(nums.length?Math.max(...nums):0)+1;return prefix+"-"+String(n).padStart(prefix==="INC"?2:3,"0")}
function initial(name){return String(name||"?").split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase()}
function stamp(){return new Date().toISOString()}
function stat(v){const s=String(v||"").toLowerCase();if(/critical|overdue|blocked|maintenance|escalat|variance|high load/.test(s))return"bad";if(/pending|delayed|review|high/.test(s))return"warn";if(/approved|posted|confirmed|available|balanced|verified|nominal|ready|contained|in progress/.test(s))return"good";return"neutral"}
function av(name,cls=""){return '<span class="avatar avatar-main '+cls+'">'+esc(initial(name))+"</span>"}
function btn(action,label,kind=""){return'<button class="button '+kind+'" data-action="'+esc(action)+'" type="button">'+esc(label)+"</button>"}
function page(id,actions=""){const r=ROUTES[id];return'<div class="page-head"><div><span class="eyebrow">'+r[1]+'</span><h1 class="page-title">'+r[2]+'</h1><p class="page-copy">'+r[3]+'</p></div><div class="page-actions">'+actions+"</div></div>"}
function findPerson(id){return state.people.find(p=>p.id===id)}
function parseHash(){const h=location.hash.replace(/^#\/?/,"");return ROUTES[h]?h:null}
function navigate(id){if(!ROUTES[id])return;route=id;location.hash="/"+id;closeAll();render();window.scrollTo({top:0,behavior:"smooth"})}

function render(){const authPage=route==="login"||route==="register";if(!state.session.authenticated&&!authPage)route="login";document.documentElement.dataset.theme=state.theme;document.body.classList.toggle("focus-mode",state.focus);document.body.classList.toggle("compact-mode",state.compact);document.body.classList.toggle("auth-mode",authPage);const view=views[route]||views.today;document.getElementById("workspace-root").innerHTML=view();document.getElementById("crumb-current").textContent=ROUTES[route]?.[0]||"Today";document.getElementById("profile-name").textContent=state.profile.name;document.getElementById("profile-role").textContent=state.profile.role;document.querySelectorAll(".avatar-main").forEach(x=>x.textContent=initial(state.profile.name));document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.route===route));const unread=state.messages.filter(m=>!m.read).length;document.getElementById("notification-count").textContent=state.notifications?unread:0;const dots={messages:state.notifications?unread:0,queue:state.tasks.filter(t=>/blocked|overdue/i.test(t.status)).length,incidents:state.incidents.filter(i=>i.state!=="Resolved").length,pharmacy:state.pharmacy.filter(p=>p.qty<p.minimum).length};document.querySelectorAll("[data-dot]").forEach(x=>x.classList.toggle("show",dots[x.dataset.dot]>0));document.title="AVERIS — "+(ROUTES[route]?.[0]||"Today")+" · by Mahi"}
function pulse(){const values=[40,48,44,58,51,68,61,75,69,82,74,88],w=760,h=220,p=28,pts=values.map((v,i)=>[p+i*(w-p*2)/(values.length-1),h-p-(v-20)/80*(h-p*2)]),line=pts.map((x,i)=>(i?"L":"M")+x[0].toFixed(1)+" "+x[1].toFixed(1)).join(" ");return'<svg viewBox="0 0 '+w+' '+h+'" aria-label="Operating pulse chart"><defs><linearGradient id="pulse" x1="0" y1="0" x2="1" y2="0"><stop stop-color="#5ef0da"/><stop offset=".55" stop-color="#7593ff"/><stop offset="1" stop-color="#ffc86b"/></linearGradient></defs><path d="M28 48H732M28 98H732M28 148H732M28 198H732" stroke="currentColor" opacity=".08"/><path d="'+line+'" fill="none" stroke="url(#pulse)" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/>'+pts.map(x=>'<circle cx="'+x[0]+'" cy="'+x[1]+'" r="3.5" fill="var(--solid)" stroke="#5ef0da" stroke-width="2"/>').join("")+"</svg>"}

function authShell(mode){
const register=mode==="register";
const title=register?"Create your AVERIS workspace":"Welcome back to AVERIS";
const subtitle=register?"Build a local synthetic control room in a few seconds.":"Sign in to your local operations workspace.";
const art=register?"./assets/care-team.svg":"./assets/healthcare-scene.svg";
const form=register?
'<form class="auth-form" data-auth-form="register" novalidate><div class="field"><label for="auth-name">Full name</label><input class="input" id="auth-name" autocomplete="name" placeholder="Mahi" required></div><div class="field"><label for="auth-email">Email</label><input class="input" id="auth-email" type="email" autocomplete="email" placeholder="mahi@averis.local" required></div><div class="field"><label for="auth-password">Password</label><div class="password-wrap"><input class="input" id="auth-password" type="password" autocomplete="new-password" minlength="6" placeholder="Minimum 6 characters" required><button class="password-toggle" data-action="toggle-password" type="button" aria-label="Show password">◉</button></div></div><div class="field"><label for="auth-confirm">Confirm password</label><input class="input" id="auth-confirm" type="password" autocomplete="new-password" minlength="6" placeholder="Repeat password" required></div><label class="check-row"><input id="auth-local-only" type="checkbox" required><span>I understand this account is local and synthetic only.</span></label><button class="button primary auth-submit" type="submit">Create workspace</button></form>':
'<form class="auth-form" data-auth-form="login" novalidate><div class="field"><label for="auth-email">Email</label><input class="input" id="auth-email" type="email" autocomplete="email" placeholder="mahi@averis.local" required></div><div class="field"><label for="auth-password">Password</label><div class="password-wrap"><input class="input" id="auth-password" type="password" autocomplete="current-password" placeholder="Your local password" required><button class="password-toggle" data-action="toggle-password" type="button" aria-label="Show password">◉</button></div></div><label class="check-row"><input id="auth-remember" type="checkbox" checked><span>Keep this browser session active</span></label><button class="button primary auth-submit" type="submit">Sign in locally</button></form>';
const opposite=register?'<button class="button ghost" data-action="open-login" type="button">Already have an account</button>':'<button class="button ghost" data-action="open-register" type="button">Create a local account</button>';
return'<section class="auth-screen"><div class="auth-stage"><div class="auth-visual"><div class="auth-image-frame"><img src="'+art+'" alt="'+(register?"Abstract local care coordination network":"Abstract healthcare operations environment")+'"><span class="image-badge"><i></i> SIMULATED / LOCAL</span></div><div class="auth-visual-copy"><span class="eyebrow">AVERIS · BY MAHI</span><h2>Operational clarity, <span>without the clinical risk.</span></h2><p>Coordinate synthetic people, work, capacity, messages, incidents and reporting from one local-first control room.</p><div class="auth-pills"><span>18 workspaces</span><span>Offline-ready</span><span>No external AI</span></div></div></div><div class="auth-card"><span class="eyebrow">'+(register?"ACCOUNT SETUP":"LOCAL ACCESS")+'</span><h1>'+title+'</h1><p>'+subtitle+'</p>'+form+(register?"":'<button class="button ghost" data-action="login-demo" type="button">Use demo Mahi account</button>')+'<div class="auth-divider"><span>local browser workspace</span></div><div class="auth-switch">'+opposite+'</div><div class="auth-footnote">Synthetic data only · no real patient records · no production integration</div></div></div></section>';
}
function loginView(){return authShell("login")}
function registerView(){return authShell("register")}
function loginNow(){
const email=(document.getElementById("auth-email")?.value||"").trim().toLowerCase();
const password=document.getElementById("auth-password")?.value||"";
if(!email||!password){toast("Sign in needs both fields","Enter your local email and password.","warn");return}
if(email!==String(state.account.email||"").toLowerCase()||localHash(password)!==state.account.passHash){toast("Sign in failed","That local account does not match. Use the demo account or register again.","warn");return}
state.profile.name=state.account.name;state.session={authenticated:true,lastLogin:stamp()};audit("Signed in","Local account");save();navigate("today");toast("Welcome back",state.profile.name+" · local session active");
}
function loginDemo(){
state.account={name:"Mahi",email:"mahi@averis.local",passHash:localHash("Mahi@580")};
state.profile.name="Mahi";state.profile.role="Control room owner";state.session={authenticated:true,lastLogin:stamp()};audit("Used demo account","Local account");save();navigate("today");toast("Demo account active","mahi@averis.local");
}
function registerNow(){
const name=(document.getElementById("auth-name")?.value||"").trim();
const email=(document.getElementById("auth-email")?.value||"").trim().toLowerCase();
const password=document.getElementById("auth-password")?.value||"";
const confirmPassword=document.getElementById("auth-confirm")?.value||"";
const localOnly=document.getElementById("auth-local-only")?.checked;
if(name.length<2){toast("Name required","Enter at least 2 characters.","warn");return}
if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){toast("Email required","Enter a valid email format.","warn");return}
if(password.length<6){toast("Password too short","Use at least 6 characters for this local simulation.","warn");return}
if(password!==confirmPassword){toast("Passwords do not match","Re-enter the same password.","warn");return}
if(!localOnly){toast("Local acknowledgement required","Confirm that this workspace is synthetic and browser-local.","warn");return}
state.account={name,email,passHash:localHash(password)};state.profile.name=name;state.profile.role="Control room owner";state.session={authenticated:true,lastLogin:stamp()};audit("Registered local account",email);save();navigate("today");toast("Workspace created","Account saved locally in this browser.");
}
function logout(){state.session.authenticated=false;save();closeAll();route="login";location.hash="/login";render();toast("Signed out","Local session ended. Your synthetic data remains in this browser.")}


function todayExtras(){return '<section class="rich-command-grid"><section class="card pad departments-card"><div class="card-head"><div><h3>Operational departments</h3><p>Visual lanes for the synthetic care environment</p></div><span class="status good">LIVE</span></div><div class="department-grid">'+[
["Emergency","12 items","./assets/healthcare-scene.svg","bad","queue"],
["Diagnostics","8 items","./assets/care-network.svg","good","diagnostics"],
["Pharmacy","3 low-stock","./assets/care-team.svg","warn","pharmacy"],
["Coordination","6 active","./assets/people.svg","good","people"],
["Capacity","4 pressure","./assets/operations.svg","warn","capacity"],
["Quality","96% signal","./assets/operational-pulse.svg","good","quality"]
].map(x=>'<button class="department-tile '+x[3]+'" data-action="go-'+x[4]+'" type="button"><span class="department-image"><img src="'+x[2]+'" alt=""></span><span class="department-copy"><b>'+x[0]+'</b><small>'+x[1]+'</small></span><span class="department-arrow">↗</span></button>').join("")+'</div></section><aside class="card pad resource-card"><div class="card-head"><div><h3>Resource utilization</h3><p>Live local capacity pressure</p></div><span class="micro mono">6 RESOURCES</span></div><div class="ring-grid">'+state.resources.slice().sort((a,b)=>b.util-a.util).slice(0,4).map(r=>'<div class="ring-wrap"><div class="ring" style="--deg:'+Math.max(0,Math.min(360,r.util*3.6))+'deg"><b>'+r.util+'%</b></div><small>'+esc(r.name)+'</small><em>'+esc(r.state)+'</em></div>').join("")+'</div></aside></section><section class="card pad activity-card"><div class="card-head"><div><h3>Recent activity</h3><p>Everything shown is generated locally in this browser.</p></div><button class="button small ghost" data-action="go-insights" type="button">View analytics ↗</button></div><div class="activity-feed">'+state.audit.slice().reverse().slice(0,6).map((a,i)=>'<div class="activity-row"><span class="activity-icon i-'+(i%5)+'">'+["↗","✓","✦","◌","!"][i%5]+'</span><div><b>'+esc(a.action)+'</b><small>'+esc(a.target)+'</small></div><time>'+esc(a.time.replace("T"," ").replace("Z",""))+'</time></div>').join("")+'</div></section>'}

function today(){const open=state.tasks.filter(t=>t.status!=="Done").length,over=state.tasks.filter(t=>/overdue/i.test(t.status)).length,unread=state.messages.filter(m=>!m.read).length,load=Math.round(state.resources.reduce((a,r)=>a+r.util,0)/state.resources.length),alerts=state.people.filter(p=>p.attention==="Escalated");const sig=[["Open work",open,over+" overdue","◫",over?"warn":"up"],["People to watch",state.people.filter(p=>p.attention!=="Monitoring").length,"active attention set","◉","up"],["Unread",unread,"responses waiting","✉",unread?"warn":"up"],["Resource load",load+"%",load>78?"pressure rising":"within range","▦",load>78?"warn":"up"]];return(state.focus?'<div class="focus-banner"><span><b>Focus mode</b> is active — key signals stay visible.</span>'+btn("toggle-focus","Exit focus","small")+"</div>":"")+
'<section class="hero"><div class="hero-copy"><div class="hero-kicker"><span class="led"></span> LIVE SYNTHETIC OPERATIONS · LOCAL ONLY</div><h1>What matters <span>right now?</span></h1><p>AVERIS is a cinematic coordination cockpit for portfolio simulation. It connects people, work, capacity, messages, incidents, and analytics without touching real healthcare systems.</p><div class="hero-actions">'+btn("open-command","⌕ Command search","primary")+btn("quick-add","＋ Create record","ghost")+btn("go-insights","◫ Open analytics","ghost")+'</div><div class="hero-stats"><div class="hero-stat"><b>'+String(open).padStart(2,"0")+'</b><span>Open work</span></div><div class="hero-stat"><b>'+String(state.appointments.length).padStart(2,"0")+'</b><span>Flow slots</span></div><div class="hero-stat"><b>'+String(state.incidents.filter(i=>i.state!=="Resolved").length).padStart(2,"0")+'</b><span>Active incidents</span></div></div></div><div class="hero-visual"><div class="hero-photo"><img src="./assets/healthcare-scene.svg" alt="Abstract healthcare operations environment"></div><img src="./assets/care-network.svg" alt="Abstract AVERIS synthetic operations network"><div class="floating-chip chip-a"><span class="pulse-dot"></span><div><b>Control core</b><small>stable</small></div></div><div class="floating-chip chip-b"><span class="pulse-dot"></span><div><b>Signals</b><small>24 live</small></div></div><div class="floating-chip chip-c"><span class="pulse-dot"></span><div><b>Boundary</b><small>local</small></div></div></div></section>'+
'<section class="signal-grid">'+sig.map(s=>'<article class="signal"><div class="signal-top"><span>'+s[0]+'</span><span class="signal-icon">'+s[3]+'</span></div><div class="signal-value">'+s[1]+'</div><div class="signal-detail"><span class="'+s[4]+'">●</span>'+s[2]+'</div></article>').join("")+'</section>'+
'<div class="workspace-grid"><section class="card pad"><div class="card-head"><div><h3>Operating pulse</h3><p>Animated synthetic workload signal</p></div><span class="micro mono">v7.0 / LOCAL</span></div><div class="chart">'+pulse()+'</div><div class="divider"></div><div class="small-grid"><div class="small-stat"><small>On-time</small><b>94.2%</b></div><div class="small-stat"><small>Queue aging</small><b>18m</b></div><div class="small-stat"><small>Response</small><b>6m</b></div></div></section><aside class="stack"><section class="card pad"><div class="card-head"><div><h3>Attention radar</h3><p>Escalated records first</p></div></div><div class="alert-list">'+(alerts.length?alerts.slice(0,3).map(p=>'<button class="alert-row critical" data-open-person="'+p.id+'" type="button"><span class="alert-icon">!</span><div><b>'+p.name+'</b><p>'+p.cluster+' · '+p.owner+'</p></div><small>open</small></button>').join(""):'<div class="empty"><b>Quiet lane</b>No escalations in this sample.</div>')+'</div></section><section class="card pad"><div class="card-head"><div><h3>Capacity pressure</h3><p>Top synthetic resources</p></div></div><div class="bar-list">'+state.resources.slice().sort((a,b)=>b.util-a.util).slice(0,4).map(r=>'<div class="bar-row"><span>'+r.name+'</span><div class="bar-track"><div class="bar-fill" style="width:'+r.util+'%"></div></div><b>'+r.util+'%</b></div>').join("")+'</div></section></aside></div>'+
'<section class="grid cols-2" style="margin-top:13px"><section class="network card"><img src="./assets/operational-pulse.svg" alt="Abstract operational pulse"><div class="network-tag"><i></i> Network activity · synthetic</div></section><section class="card pad"><div class="card-head"><div><h3>Next moves</h3><p>Real controls linked to local state</p></div></div><div class="timeline">'+state.tasks.slice(0,5).map(t=>'<div class="timeline-item"><div class="timeline-time">'+t.due.replace("Due ","")+'</div><div class="timeline-rail"><span class="timeline-dot '+stat(t.status)+'"></span></div><button class="timeline-card" data-open-task="'+t.id+'" type="button"><div class="timeline-title">'+t.title+'</div><div class="timeline-meta"><span>'+t.person+'</span><span>·</span><span>'+t.status+'</span></div></button></div>').join("")+'</div></section></section><div class="footer-note">Synthetic / local simulation. No diagnosis, treatment recommendations, real patient linkage, production integration, or external AI calls.</div>'}

function people(){let list=state.people.filter(p=>(p.name+" "+p.id+" "+p.cluster+" "+p.attention+" "+p.owner).toLowerCase().includes(peopleQuery.toLowerCase()));const rank=p=>p.attention==="Escalated"?0:p.attention==="Awaiting response"?1:2;list.sort((a,b)=>peopleSort==="name"?a.name.localeCompare(b.name):peopleSort==="updated"?b.updated-a.updated:peopleSort==="location"?a.cluster.localeCompare(b.cluster):rank(a)-rank(b));return page("people",btn("new-person","＋ New person","primary"))+'<section class="card pad"><div class="filters"><input id="people-query" class="input filter" value="'+esc(peopleQuery)+'" placeholder="Search name, ID, cluster, attention…"><div class="segments">'+["attention","name","updated","location"].map(x=>'<button type="button" '+(peopleSort===x?'class="active"':"")+' data-people-sort="'+x+'">'+(x==="attention"?"Attention":x==="updated"?"Updated":x[0].toUpperCase()+x.slice(1))+"</button>").join("")+'</div>'+btn("refresh-view","↻ Refresh","small")+'</div></section><section class="people-grid" style="margin-top:12px">'+list.map(p=>'<article class="person-card"><div class="person-main">'+av(p.name)+'<div class="person-id"><b>'+p.name+'</b><small>'+p.id+' · '+p.cluster+'</small></div></div><div class="tags"><span class="status '+stat(p.attention)+'">'+p.attention+'</span><span class="tag">'+p.journey+'</span><span class="tag">'+p.owner+'</span></div><div class="person-foot"><div class="mini-metric"><b>'+p.slot+'</b><small>NEXT SLOT</small></div><button class="button small" data-open-person="'+p.id+'" type="button">Open profile</button></div></article>').join("")+'</section>'}

function journeys(){const stages=[["Intake",state.people.filter(p=>/ONBOARDING/.test(p.journey)).length],["Work",state.people.filter(p=>/DIAGNOSTIC|FOLLOWUP/.test(p.journey)).length],["Review",state.people.filter(p=>/REVIEW/.test(p.journey)).length],["Exception",state.people.filter(p=>/ESCALATED/.test(p.journey)).length],["Close",state.people.filter(p=>/DISCHARGE/.test(p.journey)).length]];return page("journeys",btn("new-person","＋ Start synthetic journey","primary"))+'<section class="card pad"><div class="card-head"><div><h3>Journey runway</h3><p>Current distribution of the synthetic coordination sample</p></div><span class="status good">Stable flow</span></div><div class="journey">'+stages.map(x=>'<div class="journey-stage"><b>'+x[0]+'</b><strong>'+x[1]+'</strong><small>people in stage</small></div>').join("")+'</div></section><section class="grid cols-2" style="margin-top:13px"><section class="card pad"><div class="card-head"><div><h3>Friction lanes</h3><p>Open the person context</p></div></div><div class="alert-list">'+state.people.filter(p=>p.attention!=="Monitoring").slice(0,6).map(p=>'<button class="alert-row" data-open-person="'+p.id+'" type="button"><span class="alert-icon">↗</span><div><b>'+p.name+'</b><p>'+p.attention+' · '+p.journey+'</p></div><small>inspect</small></button>').join("")+'</div></section><section class="card pad"><div class="card-head"><div><h3>Journey health</h3><p>Derived from local synthetic signals</p></div></div><div class="ring-grid"><div class="ring" style="--v:88"><span><b>88%</b><small>FLOW</small></span></div><div class="ring" style="--v:72"><span><b>72%</b><small>HANDOFF</small></span></div><div class="ring" style="--v:94"><span><b>94%</b><small>TRACE</small></span></div><div class="ring" style="--v:81"><span><b>81%</b><small>RESPOND</small></span></div></div></section></section>'}

function queue(){const list=state.tasks.filter(t=>t.status!=="Done");return page("queue",btn("new-task","＋ New task","primary"))+'<section class="card pad"><div class="filters"><input id="queue-query" class="input filter" placeholder="Search task, person, owner…"><div class="segments"><button class="active" data-qfilter="all" type="button">All</button><button data-qfilter="critical" type="button">Critical</button><button data-qfilter="blocked" type="button">Blocked</button><button data-qfilter="open" type="button">Open</button></div></div><div class="table-wrap"><table><thead><tr><th>Work</th><th>Person</th><th>Priority</th><th>Due</th><th>State</th><th>Action</th></tr></thead><tbody>'+list.map(t=>'<tr><td><b>'+t.title+'</b><div class="micro mono">'+t.id+'</div></td><td>'+t.person+'</td><td><span class="status '+stat(t.priority)+'">'+t.priority+'</span></td><td>'+t.due+'</td><td><span class="status '+stat(t.status)+'">'+t.status+'</span></td><td><button class="button small" data-open-task="'+t.id+'" type="button">Inspect</button> <button class="button small" data-action="task-state:'+t.id+'" type="button">Advance</button></td></tr>').join("")+'</tbody></table></div></section>'}
function schedule(){return page("schedule",btn("new-appointment","＋ New appointment","primary"))+'<section class="card pad"><div class="card-head"><div><h3>TodayToday movement</h3><p>Inspect slots and move them without a backend.</p></div></div><div class="table-wrap"><table><thead><tr><th>Time</th><th>Person</th><th>Resource</th><th>Type</th><th>State</th><th>Action</th></tr></thead><tbody>'+state.appointments.map(a=>'<tr><td><b>'+a.time+'</b></td><td>'+a.person+'</td><td>'+a.resource+'</td><td>'+a.type+'</td><td><span class="status '+stat(a.state)+'">'+a.state+'</span></td><td><button class="button small" data-open-appointment="'+a.id+'" type="button">Inspect</button> <button class="button small" data-action="move-appointment:'+a.id+'" type="button">Move +30m</button></td></tr>').join("")+'</tbody></table></div></section>'}
function capacity(){const avg=Math.round(state.resources.reduce((a,r)=>a+r.util,0)/state.resources.length);return page("capacity",btn("new-resource","＋ Add resource","primary"))+'<section class="grid cols-4"><div class="signal"><div class="signal-top"><span>Average load</span></div><div class="signal-value">'+avg+'%</div><div class="signal-detail">'+(avg>78?"pressure rising":"within range")+'</div></div><div class="signal"><div class="signal-top"><span>Available</span></div><div class="signal-value">'+state.resources.filter(r=>r.state==="Available").length+'</div><div class="signal-detail">ready resources</div></div><div class="signal"><div class="signal-top"><span>Occupied</span></div><div class="signal-value">'+state.resources.filter(r=>r.state==="Occupied").length+'</div><div class="signal-detail">current load</div></div><div class="signal"><div class="signal-top"><span>Maintenance</span></div><div class="signal-value">'+state.resources.filter(r=>r.state==="Maintenance").length+'</div><div class="signal-detail">offline</div></div></section><section class="card pad" style="margin-top:13px"><div class="table-wrap"><table><thead><tr><th>Resource</th><th>Type</th><th>State</th><th>Utilization</th><th>Owner</th><th>Action</th></tr></thead><tbody>'+state.resources.map(r=>'<tr><td><b>'+r.name+'</b><div class="micro mono">'+r.id+'</div></td><td>'+r.type+'</td><td><span class="status '+stat(r.state)+'">'+r.state+'</span></td><td><div class="bar-track"><div class="bar-fill" style="width:'+r.util+'%"></div></div><div class="micro">'+r.util+'%</div></td><td>'+r.owner+'</td><td><button class="button small" data-open-resource="'+r.id+'" type="button">Inspect</button></td></tr>').join("")+'</tbody></table></div></section>'}
function workforce(){return page("workforce",btn("new-workforce","＋ Add workforce","primary"))+'<section class="card pad"><div class="card-head"><div><h3>Load distribution</h3><p>Synthetic workload by team member</p></div></div><div class="bar-list">'+state.workforce.map(w=>'<div class="bar-row"><span>'+w.name+'</span><div class="bar-track"><div class="bar-fill" style="width:'+w.load+'%"></div></div><b>'+w.load+'%</b></div>').join("")+'</div></section><section class="card pad" style="margin-top:13px"><div class="table-wrap"><table><thead><tr><th>Name</th><th>Role</th><th>State</th><th>Open work</th><th>Action</th></tr></thead><tbody>'+state.workforce.map(w=>'<tr><td><b>'+w.name+'</b></td><td>'+w.role+'</td><td><span class="status '+stat(w.state)+'">'+w.state+'</span></td><td>'+Math.max(1,Math.round(w.load/22))+'</td><td><button class="button small" data-open-workforce="'+w.id+'" type="button">Inspect</button></td></tr>').join("")+'</tbody></table></div></section>'}
function diagnostics(){return page("diagnostics",btn("new-diagnostic","＋ New workflow result","primary"))+'<section class="card pad"><div class="table-wrap"><table><thead><tr><th>ID</th><th>Person</th><th>Workflow</th><th>State</th><th>Value</th><th>Action</th></tr></thead><tbody>'+state.diagnostics.map(d=>'<tr><td class="mono">'+d.id+'</td><td>'+d.person+'</td><td>'+d.type+'</td><td><span class="status '+stat(d.state)+'">'+d.state+'</span></td><td>'+d.value+'</td><td><button class="button small" data-open-diagnostic="'+d.id+'" type="button">Inspect</button></td></tr>').join("")+'</tbody></table></div></section>'}
function pharmacy(){const low=state.pharmacy.filter(p=>p.qty<p.minimum).length;return page("pharmacy",btn("new-pharmacy","＋ Add inventory","primary"))+'<section class="small-grid"><div class="small-stat"><small>SKUs</small><b>'+state.pharmacy.length+'</b></div><div class="small-stat"><small>Low stock</small><b>'+low+'</b></div><div class="small-stat"><small>Total units</small><b>'+state.pharmacy.reduce((a,p)=>a+p.qty,0)+'</b></div></section><section class="card pad" style="margin-top:13px"><div class="table-wrap"><table><thead><tr><th>Item</th><th>Quantity</th><th>Minimum</th><th>Variance</th><th>State</th><th>Action</th></tr></thead><tbody>'+state.pharmacy.map(p=>'<tr><td><b>'+p.item+'</b><div class="micro mono">'+p.id+'</div></td><td>'+p.qty+' '+p.unit+'</td><td>'+p.minimum+'</td><td>'+p.variance+'</td><td><span class="status '+(p.qty<p.minimum?"bad":"good")+'">'+(p.qty<p.minimum?"Low stock":"Healthy")+'</span></td><td><button class="button small" data-pharmacy="'+p.id+'" type="button">Adjust</button></td></tr>').join("")+'</tbody></table></div></section>'}
function finance(){return page("finance",btn("new-finance","＋ New transaction","primary"))+'<section class="grid cols-3"><div class="signal"><div class="signal-top"><span>Ledger items</span></div><div class="signal-value">'+state.finance.length+'</div><div class="signal-detail">synthetic records</div></div><div class="signal"><div class="signal-top"><span>Approved</span></div><div class="signal-value">'+state.finance.filter(f=>/approved|posted/i.test(f.state)).length+'</div><div class="signal-detail">cleared</div></div><div class="signal"><div class="signal-top"><span>Review</span></div><div class="signal-value">'+state.finance.filter(f=>/pending|review/i.test(f.state)).length+'</div><div class="signal-detail">open checks</div></div></section><section class="card pad" style="margin-top:13px"><div class="table-wrap"><table><thead><tr><th>Label</th><th>Amount</th><th>State</th><th>Date</th><th>Action</th></tr></thead><tbody>'+state.finance.map(f=>'<tr><td><b>'+f.label+'</b><div class="micro mono">'+f.id+'</div></td><td>'+f.amount+'</td><td><span class="status '+stat(f.state)+'">'+f.state+'</span></td><td>'+f.date+'</td><td><button class="button small" data-finance="'+f.id+'" type="button">Inspect</button></td></tr>').join("")+'</tbody></table></div><div style="margin-top:10px">'+btn("export-finance","⇩ Export finance JSON","small")+"</div></section>"}
function messages(){return page("messages",btn("new-message","＋ New message","primary"))+'<section class="card pad"><div class="message-list">'+state.messages.map(m=>'<button class="message '+(m.read?"":"unread")+'" data-message="'+m.id+'" type="button">'+av(m.from)+'<div><b>'+m.from+'</b><p>'+esc(m.text)+'</p></div><small>'+m.when+'</small></button>').join("")+'</div></section>'}
function incidents(){return page("incidents",btn("new-incident","＋ New incident","primary"))+'<section class="card pad"><div class="table-wrap"><table><thead><tr><th>Incident</th><th>Severity</th><th>State</th><th>Person</th><th>Owner</th><th>Action</th></tr></thead><tbody>'+state.incidents.map(i=>'<tr><td><b>'+i.title+'</b><div class="micro mono">'+i.id+'</div></td><td><span class="status '+stat(i.severity)+'">'+i.severity+'</span></td><td><span class="status '+stat(i.state)+'">'+i.state+'</span></td><td>'+i.person+'</td><td>'+i.owner+'</td><td><button class="button small" data-incident="'+i.id+'" type="button">Inspect</button></td></tr>').join("")+'</tbody></table></div></section>'}
function quality(){const checks=[["Traceability",96],["Workflow integrity",91],["Response rhythm",88],["Capacity balance",79],["Boundary compliance",100]];return page("quality",btn("run-quality","Run quality pass","primary"))+'<section class="grid cols-2">'+checks.map(c=>'<section class="card pad"><div class="card-head"><div><h3>'+c[0]+'</h3><p>Local synthetic quality indicator.</p></div><b>'+c[1]+'%</b></div><div class="bar-track"><div class="bar-fill" style="width:'+c[1]+'%"></div></div></section>').join("")+'</section>'}
function insights(){const open=state.tasks.filter(t=>t.status!=="Done").length,blocked=state.tasks.filter(t=>/blocked|overdue/i.test(t.status)).length,unread=state.messages.filter(m=>!m.read).length,load=Math.round(state.resources.reduce((a,r)=>a+r.util,0)/state.resources.length),wload=Math.round(state.workforce.reduce((a,w)=>a+w.load,0)/state.workforce.length),attention=Math.round(state.people.filter(p=>p.attention!=="Monitoring").length/state.people.length*100);const bars=[["Queue",Math.min(100,40+blocked*7)],["People",Math.min(100,45+attention)],["Capacity",load],["Workforce",wload],["Pharmacy",Math.min(100,42+state.pharmacy.filter(p=>p.qty<p.minimum).length*18)]];return page("insights",btn("export-insights","⇩ Export analytics","ghost")+" "+btn("refresh-view","↻ Refresh","primary"))+'<section class="grid cols-4">'+[["Open work",open],["Blocked",blocked],["Unread",unread],["Attention",attention+"%"]].map(x=>'<div class="signal"><div class="signal-top"><span>'+x[0]+'</span><span class="signal-icon">◫</span></div><div class="signal-value">'+x[1]+'</div><div class="signal-detail">live from local state</div></div>').join("")+'</section><section class="workspace-grid"><section class="card pad"><div class="card-head"><div><h3>Operational mix</h3><p>Normalized pressure by workspace</p></div><span class="status good">Live</span></div><div class="bar-list">'+bars.map(b=>'<div class="bar-row"><span>'+b[0]+'</span><div class="bar-track"><div class="bar-fill" style="width:'+b[1]+'%"></div></div><b>'+b[1]+'%</b></div>').join("")+'</div><div class="divider"></div>'+pulse()+'</section><section class="card pad"><div class="card-head"><div><h3>Signal distribution</h3><p>Current sample envelope</p></div></div><div class="ring-grid"><div class="ring" style="--v:94"><span><b>94%</b><small>ON-TIME</small></span></div><div class="ring" style="--v:'+(100-blocked*5)+'"><span><b>'+(100-blocked*5)+'%</b><small>FLOW</small></span></div><div class="ring" style="--v:88"><span><b>88%</b><small>RESPOND</small></span></div><div class="ring" style="--v:'+wload+'"><span><b>'+wload+'%</b><small>WORKFORCE</small></span></div></div></section></section><section class="card pad" style="margin-top:13px"><div class="card-head"><div><h3>Analytics contract</h3><p>Transparent calculations from browser-local synthetic state.</p></div></div><p class="page-copy">Every displayed metric is derived from records stored in localStorage. No external model, server request, patient connection, or hidden scoring layer is used.</p></section>'}
function assistant(){return page("assistant",btn("open-command","⌕ Search","ghost"))+'<section class="grid cols-2"><section class="card pad"><div class="card-head"><div><h3>Local assistant</h3><p>Deterministic rules, zero external calls.</p></div><span class="status good">LOCAL</span></div><div class="alert-list"><button class="alert-row" data-assistant="attention" type="button"><span class="alert-icon">✦</span><div><b>What needs attention?</b><p>Escalations and blocked work.</p></div><small>run</small></button><button class="alert-row" data-assistant="brief" type="button"><span class="alert-icon">✦</span><div><b>Summarize today</b><p>Open a compact operating brief.</p></div><small>run</small></button><button class="alert-row" data-assistant="boundary" type="button"><span class="alert-icon">✦</span><div><b>Explain the boundary</b><p>Why the system stays synthetic.</p></div><small>run</small></button></div><div style="margin-top:12px"><label class="micro">Ask the local rules engine</label><div style="display:grid;grid-template-columns:1fr auto;gap:7px;margin-top:5px"><input class="input" id="assistant-input" placeholder="show blocked work"><button class="button primary" data-action="assistant-run" type="button">Run</button></div></div></section><section class="card pad" id="assistant-output"><div class="card-head"><div><h3>Assistant output</h3><p>Local deterministic response.</p></div></div><div class="empty"><b>Ready</b>Choose a prompt or type a question.</div></section></section>'}
function reports(){return page("reports",btn("new-report","＋ New report","primary")+" "+btn("export-state","⇩ Export state","ghost"))+'<section class="report-grid">'+state.reports.map(r=>'<article class="report"><span class="eyebrow">'+r.type+'</span><h3>'+r.name+'</h3><p>Preview or run against the current synthetic browser state.</p><div class="report-foot"><span class="status '+stat(r.state)+'">'+r.state+'</span><div><button class="button small" data-report-preview="'+r.id+'" type="button">Preview</button> <button class="button small" data-report-run="'+r.id+'" type="button">Run</button></div></div></article>').join("")+'</section>'}
function auditView(){return page("audit",btn("export-audit","⇩ Export audit","ghost"))+'<section class="card pad"><div class="table-wrap"><table><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Target</th></tr></thead><tbody>'+state.audit.slice().reverse().map(a=>'<tr><td class="micro mono">'+a.time+'</td><td>'+a.actor+'</td><td>'+a.action+'</td><td>'+a.target+'</td></tr>').join("")+'</tbody></table></div></section>'}
function settings(){return page("settings",btn("save-settings","Save settings","primary"))+'<section class="grid cols-2"><section class="card pad"><div class="card-head"><div><h3>Profile</h3><p>Saved in this browser.</p></div></div><div class="form-grid"><div class="field"><label>Name</label><input class="input" id="settings-name" value="'+esc(state.profile.name)+'"></div><div class="field"><label>Role</label><input class="input" id="settings-role" value="'+esc(state.profile.role)+'"></div></div></section><section class="card pad"><div class="card-head"><div><h3>Appearance</h3><p>Theme and density.</p></div></div>'+btn("theme-toggle","Theme: "+state.theme,"ghost")+" "+btn("density-toggle","Density: "+(state.compact?"Compact":"Comfortable"),"ghost")+'</section><section class="card pad"><div class="card-head"><div><h3>Notifications</h3><p>Local unread counters.</p></div><span class="status '+(state.notifications?"good":"neutral")+'">'+(state.notifications?"On":"Off")+'</span></div>'+btn("notifications-toggle",state.notifications?"Turn off":"Turn on","ghost")+'</section><section class="card pad"><div class="card-head"><div><h3>Persistence</h3><p>Reset affects only this browserthis browser synthetic state.</p></div></div>'+btn("export-state","Export JSON","ghost")+" "+btn("reset-state","Reset state","danger")+'</section></section><section class="card pad" style="margin-top:13px"><div class="card-head"><div><h3>Boundary contract</h3><p>Portfolio simulation, not production healthcare.</p></div></div><div class="detail-grid"><div class="detail"><small>Data source</small><b>Synthetic fixtures</b></div><div class="detail"><small>Persistence</small><b>localStorage</b></div><div class="detail"><small>AI</small><b>Local rules only</b></div><div class="detail"><small>External integrations</small><b>None</b></div></div></section>'}

const views={login:loginView,register:registerView,today,people,journeys,queue,schedule,capacity,workforce,diagnostics,pharmacy,finance,messages,incidents,quality,insights,assistant,reports,audit:auditView,settings};

function showDrawer(k,t,body){const d=document.getElementById("drawer");document.getElementById("drawer-eyebrow").textContent=k;document.getElementById("drawer-title").textContent=t;document.getElementById("drawer-body").innerHTML=body;d.classList.add("open");d.setAttribute("aria-hidden","false");if(!document.getElementById("drawer-scrim")){const s=document.createElement("div");s.id="drawer-scrim";s.className="drawer-scrim";document.body.appendChild(s);s.onclick=closeDrawer}}
function closeDrawer(){document.getElementById("drawer")?.classList.remove("open");document.getElementById("drawer")?.setAttribute("aria-hidden","true");document.getElementById("drawer-scrim")?.remove()}
function closeOverlay(id){document.getElementById(id)?.setAttribute("hidden","true")}
function closeAll(){closeDrawer();closeOverlay("command-overlay");closeOverlay("modal-overlay")}
function toast(title,msg,type="good"){const s=document.getElementById("toast-stack"),e=document.createElement("div");e.className="toast";e.innerHTML='<span class="toast-icon">'+(type==="warn"?"!":type==="bad"?"×":"✓")+'</span><div><b>'+esc(title)+'</b><p>'+esc(msg)+'</p></div><button type="button">×</button>';e.lastElementChild.onclick=()=>e.remove();s.appendChild(e);setTimeout(()=>e.remove(),4500)}
function audit(action,target){state.audit.push({time:stamp(),actor:state.profile.name,action,target});if(state.audit.length>150)state.audit.shift()}
function exportJson(filename,data){const b=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(u),300);toast("Export ready",filename+" generated locally.")}
function toggleFocus(){state.focus=!state.focus;save();render();toast(state.focus?"Focus mode enabled":"Focus mode closed","")}
function quickAdd(){const k=(prompt("Create: person / task / message / incident","task")||"").trim().toLowerCase();if(k==="person")openModal("person");else if(k==="task")openModal("task");else if(k==="message")openModal("message");else if(k==="incident")openModal("incident");else toast("No record created","Choose person, task, message, or incident.","warn")}
function openCommand(){const o=document.getElementById("command-overlay");o.hidden=false;document.getElementById("command-input").value="";buildCommands("");setTimeout(()=>document.getElementById("command-input").focus(),25)}
function buildCommands(q){q=q.toLowerCase();commandItems=[];NAV.forEach(x=>{const hay=(x[1]+" "+ROUTES[x[0]].join(" ")).toLowerCase();if(!q||hay.includes(q))commandItems.push({group:"Workspace",label:x[1],sub:ROUTES[x[0]][3],icon:x[2],route:x[0]})});state.people.forEach(p=>{const hay=(p.name+" "+p.id+" "+p.cluster).toLowerCase();if(!q||hay.includes(q))commandItems.push({group:"People",label:p.name,sub:p.id+" · "+p.cluster,icon:"◉",person:p.id})});state.tasks.forEach(t=>{const hay=(t.title+" "+t.id+" "+t.person).toLowerCase();if(!q||hay.includes(q))commandItems.push({group:"Tasks",label:t.title,sub:t.id+" · "+t.person,icon:"◫",task:t.id})});commandIndex=0;const box=document.getElementById("command-results"),groups=new Set();box.innerHTML=commandItems.slice(0,20).map((x,i)=>(groups.has(x.group)?"":(groups.add(x.group),'<div class="command-group">'+x.group+"</div>"))+'<div class="command-result '+(i===0?"selected":"")+'" data-command-index="'+i+'"><span class="command-result-icon">'+x.icon+'</span><div><b>'+esc(x.label)+'</b><small>'+esc(x.sub)+'</small></div><kbd>↵</kbd></div>').join("")||'<div class="empty"><b>No result</b>Try another search.</div>'}
function openCommandItem(i){const x=commandItems[i];if(!x)return;if(x.route)navigate(x.route);else if(x.person){closeOverlay("command-overlay");openPerson(x.person)}else if(x.task){closeOverlay("command-overlay");openTask(x.task)}}
function syncCommands(){document.querySelectorAll("[data-command-index]").forEach(x=>x.classList.toggle("selected",Number(x.dataset.commandIndex)===commandIndex))}

function openPerson(id){const p=findPerson(id);if(!p)return;const tasks=state.tasks.filter(t=>t.person===p.name),apps=state.appointments.filter(a=>a.person===p.name),dx=state.diagnostics.filter(d=>d.person===p.name);showDrawer("Person profile",p.name,'<div class="person-main" style="margin-bottom:13px">'+av(p.name)+'<div class="person-id"><b style="font-size:13px">'+p.name+'</b><small>'+p.id+' · '+p.cluster+'</small></div></div><div class="detail-grid"><div class="detail"><small>Attention</small><b>'+p.attention+'</b></div><div class="detail"><small>Owner</small><b>'+p.owner+'</b></div><div class="detail"><small>Journey</small><b>'+p.journey+'</b></div><div class="detail"><small>Contact</small><b>'+p.contact+'</b></div></div><div class="drawer-section"><h3>Coordination work</h3>'+tasks.map(t=>'<button class="alert-row" data-open-task="'+t.id+'" type="button"><span class="alert-icon">•</span><div><b>'+t.title+'</b><p>'+t.status+' · '+t.owner+'</p></div><small>'+t.due+'</small></button>').join("")+'</div><div class="drawer-section"><h3>Appointments</h3>'+apps.map(a=>'<div class="kpi-row"><span>'+a.time+' · '+a.resource+'</span><b>'+a.state+'</b></div>').join("")+'</div><div class="drawer-section"><h3>Diagnostics workflow</h3>'+dx.map(d=>'<div class="kpi-row"><span>'+d.type+'</span><b>'+d.state+'</b></div>').join("")+'</div><div class="drawer-section"><h3>Notes</h3><p>'+esc(p.notes)+'</p></div><div class="pill-row">'+btn("edit-person:"+p.id,"Edit profile","primary")+btn("new-task-for:"+p.id,"＋ Add task","ghost")+"</div>")}
function openTask(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;showDrawer("Work item",t.title,'<div class="detail-grid"><div class="detail"><small>ID</small><b class="mono">'+t.id+'</b></div><div class="detail"><small>Priority</small><b>'+t.priority+'</b></div><div class="detail"><small>Person</small><b>'+t.person+'</b></div><div class="detail"><small>Owner</small><b>'+t.owner+'</b></div></div><div class="drawer-section"><h3>Current state</h3><p>'+t.status+' · '+t.due+'</p></div><div class="pill-row">'+btn("task-state:"+t.id,"Advance state","primary")+btn("reopen-task:"+t.id,"Reopen","ghost")+"</div>")}
function openModal(kind,data={}){
const ov=document.getElementById("modal-overlay"),body=document.getElementById("modal-body"),foot=document.getElementById("modal-foot");let title="New record",ey="ACTION",content="",actions="";
if(kind==="person"){ey=data.id?"EDIT PERSON":"PEOPLE";title=data.id?"Edit person":"New synthetic person";content='<div class="form-grid"><div class="field"><label>Name</label><input class="input" id="f-name" value="'+esc(data.name||"")+'"></div><div class="field"><label>Cluster</label><select class="select" id="f-cluster">'+["North cluster","Central cluster","East cluster","South cluster","West cluster"].map(v=>'<option '+(v===data.cluster?"selected":"")+'>'+v+"</option>").join("")+'</select></div><div class="field"><label>Priority</label><select class="select" id="f-priority">'+["Priority 1","Priority 2","Priority 3"].map(v=>'<option '+(v===data.priority?"selected":"")+'>'+v+"</option>").join("")+'</select></div><div class="field"><label>Owner</label><input class="input" id="f-owner" value="'+esc(data.owner||state.profile.name)+'"></div><div class="field full"><label>Notes</label><textarea class="textarea" id="f-notes">'+esc(data.notes||"Synthetic coordination note.")+"</textarea></div></div>";actions=btn("cancel-modal","Cancel","ghost")+btn(data.id?"save-person:"+data.id:"save-person","Save person","primary")}
if(kind==="task"){ey="QUEUE";title="New coordination task";content='<div class="form-grid"><div class="field full"><label>Title</label><input class="input" id="f-task-title" placeholder="Describe the work"></div><div class="field"><label>Person</label><select class="select" id="f-task-person">'+state.people.map(p=>'<option>'+p.name+"</option>").join("")+'</select></div><div class="field"><label>Priority</label><select class="select" id="f-task-priority"><option>High</option><option>Critical</option><option>Medium</option><option>Low</option></select></div></div>';actions=btn("cancel-modal","Cancel","ghost")+btn("save-task","Create task","primary")}
if(kind==="message"){ey="MESSAGES";title="New local message";content='<div class="form-grid"><div class="field"><label>Recipient</label><select class="select" id="f-message-to"><option>Asha</option><option>Ravi</option><option>Maya</option><option>Sanjay</option></select></div><div class="field"><label>Subject</label><input class="input" id="f-message-subject" placeholder="Short subject"></div><div class="field full"><label>Message</label><textarea class="textarea" id="f-message-text" placeholder="Write a simulated message"></textarea></div></div>';actions=btn("cancel-modal","Cancel","ghost")+btn("save-message","Send locally","primary")}
if(kind==="incident"){ey="INCIDENTS";title="New simulated incident";content='<div class="form-grid"><div class="field full"><label>Title</label><input class="input" id="f-incident-title"></div><div class="field"><label>Severity</label><select class="select" id="f-incident-severity"><option>High</option><option>Medium</option><option>Low</option></select></div><div class="field"><label>Person</label><select class="select" id="f-incident-person">'+state.people.map(p=>'<option>'+p.id+"</option>").join("")+'</select></div><div class="field full"><label>Note</label><textarea class="textarea" id="f-incident-note">Synthetic incident record. No external action is initiated.</textarea></div></div>';actions=btn("cancel-modal","Cancel","ghost")+btn("save-incident","Create incident","primary")}
if(kind==="appointment"){ey="SCHEDULE";title="New synthetic appointment";content='<div class="form-grid"><div class="field"><label>Person</label><select class="select" id="f-ap-person">'+state.people.map(p=>'<option>'+p.name+"</option>").join("")+'</select></div><div class="field"><label>Time</label><input class="input" id="f-ap-time" type="time" value="10:30"></div><div class="field"><label>Resource</label><select class="select" id="f-ap-resource">'+state.resources.filter(r=>r.state!=="Maintenance").map(r=>'<option>'+r.name+"</option>").join("")+'</select></div><div class="field"><label>Type</label><select class="select" id="f-ap-type"><option>Review</option><option>Coordination</option><option>Follow-up</option><option>Diagnostic workflow</option></select></div></div>';actions=btn("cancel-modal","Cancel","ghost")+btn("save-appointment","Create appointment","primary")}
if(kind==="resource"){ey="CAPACITY";title="Add synthetic resource";content='<div class="form-grid"><div class="field"><label>Name</label><input class="input" id="f-r-name" placeholder="Atlas Room"></div><div class="field"><label>Type</label><select class="select" id="f-r-type"><option>Room</option><option>Virtual</option><option>Pod</option></select></div><div class="field"><label>State</label><select class="select" id="f-r-state"><option>Available</option><option>Occupied</option><option>Maintenance</option></select></div><div class="field"><label>Utilization %</label><input class="input" id="f-r-util" type="number" min="0" max="100" value="45"></div><div class="field full"><label>Owner</label><input class="input" id="f-r-owner" value="Team A"></div></div>';actions=btn("cancel-modal","Cancel","ghost")+btn("save-resource","Create resource","primary")}
if(kind==="workforce"){ey="WORKFORCE";title="Add synthetic workforce";content='<div class="form-grid"><div class="field"><label>Name</label><input class="input" id="f-w-name" placeholder="New coordinator"></div><div class="field"><label>Role</label><input class="input" id="f-w-role" value="Coordinator"></div><div class="field"><label>State</label><select class="select" id="f-w-state"><option>Available</option><option>Balanced</option><option>High load</option></select></div><div class="field"><label>Load %</label><input class="input" id="f-w-load" type="number" min="0" max="100" value="40"></div></div>';actions=btn("cancel-modal","Cancel","ghost")+btn("save-workforce","Create workforce","primary")}
if(kind==="diagnostic"){ey="DIAGNOSTICS";title="New workflow result";content='<div class="form-grid"><div class="field"><label>Person</label><select class="select" id="f-d-person">'+state.people.map(p=>'<option>'+p.name+"</option>").join("")+'</select></div><div class="field"><label>Workflow</label><select class="select" id="f-d-type"><option>Workflow result</option><option>Imaging workflow</option><option>Lab workflow</option></select></div><div class="field"><label>State</label><select class="select" id="f-d-state"><option>Received</option><option>Review</option><option>Verified</option><option>Queued</option></select></div><div class="field"><label>Value</label><input class="input" id="f-d-value" value="Nominal"></div></div>';actions=btn("cancel-modal","Cancel","ghost")+btn("save-diagnostic","Create result","primary")}
if(kind==="pharmacy"){ey="PHARMACY";title="Add inventory item";content='<div class="form-grid"><div class="field"><label>Item</label><input class="input" id="f-p-item" placeholder="Nova-07"></div><div class="field"><label>Unit</label><select class="select" id="f-p-unit"><option>Unit</option><option>Pack</option></select></div><div class="field"><label>Quantity</label><input class="input" id="f-p-qty" type="number" min="0" value="200"></div><div class="field"><label>Minimum</label><input class="input" id="f-p-min" type="number" min="0" value="100"></div><div class="field"><label>Variance</label><input class="input" id="f-p-var" type="number" min="0" value="0"></div></div>';actions=btn("cancel-modal","Cancel","ghost")+btn("save-pharmacy","Add inventory","primary")}
if(kind==="finance"){ey="FINANCE";title="New synthetic finance item";content='<div class="form-grid"><div class="field full"><label>Label</label><input class="input" id="f-f-label" placeholder="Operations allocation"></div><div class="field"><label>Amount</label><input class="input" id="f-f-amount" placeholder="+₹12,000"></div><div class="field"><label>State</label><select class="select" id="f-f-state"><option>Pending</option><option>Approved</option><option>Posted</option><option>Review</option></select></div><div class="field full"><label>Date label</label><input class="input" id="f-f-date" value="Today"></div></div>';actions=btn("cancel-modal","Cancel","ghost")+btn("save-finance","Create finance item","primary")}
if(kind==="report"){ey="REPORTS";title="New local report template";content='<div class="form-grid"><div class="field full"><label>Report name</label><input class="input" id="f-rep-name" placeholder="Evening operations brief"></div><div class="field"><label>Type</label><select class="select" id="f-rep-type"><option>Operational</option><option>Execution</option><option>Capacity</option><option>Quality</option></select></div></div>';actions=btn("cancel-modal","Cancel","ghost")+btn("save-report","Create report","primary")}
document.getElementById("modal-eyebrow").textContent=ey;document.getElementById("modal-title").textContent=title;body.innerHTML=content;foot.innerHTML=actions;ov.hidden=false;setTimeout(()=>body.querySelector("input,select,textarea")?.focus(),25)}
function savePerson(id){const name=document.getElementById("f-name").value.trim();if(!name){toast("Name required","Enter a person name.","warn");return}if(id){const p=findPerson(id);if(p){p.name=name;p.cluster=document.getElementById("f-cluster").value;p.priority=document.getElementById("f-priority").value;p.owner=document.getElementById("f-owner").value||state.profile.name;p.notes=document.getElementById("f-notes").value;audit("Edited person",p.id)}}else{const p={id:nextId("P",state.people),name,cluster:document.getElementById("f-cluster").value,priority:document.getElementById("f-priority").value,slot:"Unscheduled",journey:"JOURNEY-NEW",attention:"Monitoring",updated:Date.now(),owner:document.getElementById("f-owner").value||state.profile.name,contact:"Portal",notes:document.getElementById("f-notes").value};state.people.unshift(p);audit("Created person",p.id)}save();closeOverlay("modal-overlay");render();toast("Person saved",name)}
function saveTask(){const title=document.getElementById("f-task-title").value.trim();if(!title){toast("Task title required","Enter a task title.","warn");return}const t={id:nextId("T",state.tasks),title,person:document.getElementById("f-task-person").value,priority:document.getElementById("f-task-priority").value,due:"Due "+new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}),status:"Open",owner:state.profile.name,updated:Date.now()};state.tasks.unshift(t);audit("Created task",t.id);save();closeOverlay("modal-overlay");render();toast("Task created",title)}
function saveMessage(){const text=document.getElementById("f-message-text").value.trim();if(!text){toast("Message empty","Write a message.","warn");return}const m={id:nextId("M",state.messages),from:state.profile.name,text:"To "+document.getElementById("f-message-to").value+": "+text,when:"just now",read:true,reply:""};state.messages.unshift(m);audit("Sent message",m.id);save();closeOverlay("modal-overlay");render();toast("Message sent locally","No external service was contacted.")}
function saveIncident(){const title=document.getElementById("f-incident-title").value.trim();if(!title){toast("Incident title required","Describe the simulated incident.","warn");return}const i={id:nextId("INC",state.incidents),title,severity:document.getElementById("f-incident-severity").value,state:"Open",person:document.getElementById("f-incident-person").value,owner:state.profile.name,opened:"Now",note:document.getElementById("f-incident-note").value};state.incidents.unshift(i);audit("Created incident",i.id);save();closeOverlay("modal-overlay");render();toast("Incident created",i.id)}
function saveAppointment(){const a={id:nextId("A",state.appointments),time:document.getElementById("f-ap-time").value||"10:30",person:document.getElementById("f-ap-person").value,resource:document.getElementById("f-ap-resource").value,type:document.getElementById("f-ap-type").value,state:"Confirmed"};state.appointments.push(a);audit("Created appointment",a.id);save();closeOverlay("modal-overlay");render();toast("Appointment created",a.id)}
function saveResource(){const r={id:nextId("R",state.resources),name:document.getElementById("f-r-name").value.trim()||"New resource",type:document.getElementById("f-r-type").value,state:document.getElementById("f-r-state").value,util:Math.max(0,Math.min(100,Number(document.getElementById("f-r-util").value)||0)),owner:document.getElementById("f-r-owner").value.trim()||"Team A"};state.resources.push(r);audit("Created resource",r.id);save();closeOverlay("modal-overlay");render();toast("Resource created",r.name)}
function saveWorkforce(){const w={id:nextId("W",state.workforce),name:document.getElementById("f-w-name").value.trim()||"New member",role:document.getElementById("f-w-role").value.trim()||"Coordinator",state:document.getElementById("f-w-state").value,load:Math.max(0,Math.min(100,Number(document.getElementById("f-w-load").value)||0))};state.workforce.push(w);audit("Created workforce",w.id);save();closeOverlay("modal-overlay");render();toast("Workforce created",w.name)}
function saveDiagnostic(){const d={id:nextId("DX",state.diagnostics),person:document.getElementById("f-d-person").value,type:document.getElementById("f-d-type").value,state:document.getElementById("f-d-state").value,value:document.getElementById("f-d-value").value.trim()||"Nominal"};state.diagnostics.push(d);audit("Created diagnostic workflow",d.id);save();closeOverlay("modal-overlay");render();toast("Workflow result created",d.id)}
function savePharmacy(){const item=document.getElementById("f-p-item").value.trim();if(!item){toast("Item required","Enter an inventory item.","warn");return}const p={id:nextId("RX",state.pharmacy),item,unit:document.getElementById("f-p-unit").value,qty:Number(document.getElementById("f-p-qty").value)||0,minimum:Number(document.getElementById("f-p-min").value)||0,variance:Number(document.getElementById("f-p-var").value)||0};state.pharmacy.push(p);audit("Created inventory item",p.id);save();closeOverlay("modal-overlay");render();toast("Inventory added",item)}
function saveFinance(){const label=document.getElementById("f-f-label").value.trim();if(!label){toast("Label required","Enter a finance item.","warn");return}const f={id:nextId("F",state.finance),label,amount:document.getElementById("f-f-amount").value.trim()||"₹0",state:document.getElementById("f-f-state").value,date:document.getElementById("f-f-date").value.trim()||"Today"};state.finance.push(f);audit("Created finance item",f.id);save();closeOverlay("modal-overlay");render();toast("Finance item created",label)}
function saveReport(){const name=document.getElementById("f-rep-name").value.trim();if(!name){toast("Report name required","Enter a report name.","warn");return}const r={id:nextId("REP",state.reports),name:name,type:document.getElementById("f-rep-type").value,state:"Draft",updated:"just now"};state.reports.push(r);audit("Created report",r.id);save();closeOverlay("modal-overlay");render();toast("Report created",name)}

function handleAction(a){if(a.startsWith("go-")&&ROUTES[a.slice(3)]){navigate(a.slice(3));return}if(a==="assistant-run"){const q=(document.getElementById("assistant-input")?.value||"").toLowerCase();if(!q){toast("Ask the local assistant","Type a question first.","warn");return}answerAssistant(/attention|blocked|late|urgent/.test(q)?"attention":/summary|today|brief|open/.test(q)?"brief":"boundary");return}

if(a==="open-login"){navigate("login");return}if(a==="open-register"){navigate("register");return}if(a==="login-demo"){loginDemo();return}if(a==="logout"){logout();return}if(a==="toggle-password"){const x=document.getElementById("auth-password");if(x){x.type=x.type==="password"?"text":"password";document.querySelectorAll(".password-toggle").forEach(b=>b.textContent=x.type==="password"?"◉":"◌")}return}
if(a==="open-command"){openCommand();return}if(a==="quick-add"){quickAdd();return}if(a==="go-insights"){navigate("insights");return}if(a==="go-settings"){navigate("settings");return}if(a==="toggle-focus"){toggleFocus();return}
if(a==="new-person"){openModal("person");return}if(a==="new-task"){openModal("task");return}if(a==="new-message"){openModal("message");return}if(a==="new-incident"){openModal("incident");return}
if(a==="new-appointment"){openModal("appointment");return}if(a==="new-resource"){openModal("resource");return}if(a==="new-workforce"){openModal("workforce");return}if(a==="new-diagnostic"){openModal("diagnostic");return}if(a==="new-pharmacy"){openModal("pharmacy");return}if(a==="new-finance"){openModal("finance");return}if(a==="new-report"){openModal("report");return}
if(a==="cancel-modal"){closeOverlay("modal-overlay");return}if(a==="save-appointment"){saveAppointment();return}if(a==="save-resource"){saveResource();return}if(a==="save-workforce"){saveWorkforce();return}if(a==="save-diagnostic"){saveDiagnostic();return}if(a==="save-pharmacy"){savePharmacy();return}if(a==="save-finance"){saveFinance();return}if(a==="save-report"){saveReport();return}if(a.startsWith("save-person:")){savePerson(a.split(":")[1]);return}if(a==="save-person"){savePerson();return}if(a==="save-task"){saveTask();return}if(a==="save-message"){saveMessage();return}if(a==="save-incident"){saveIncident();return}
if(a==="theme-toggle"){state.theme=state.theme==="dark"?"light":"dark";save();render();toast("Theme switched",state.theme+" mode active");return}if(a==="density-toggle"){state.compact=!state.compact;save();toast("Density changed",state.compact?"Compact":"Comfortable");return}if(a==="notifications-toggle"){state.notifications=!state.notifications;save();render();toast("Notifications "+(state.notifications?"enabled":"disabled"));return}if(a==="save-settings"){state.profile.name=document.getElementById("settings-name").value.trim()||"Mahi";state.profile.role=document.getElementById("settings-role").value.trim()||"Control room owner";audit("Saved settings","Profile");save();render();toast("Settings saved","Local preferences updated.");return}
if(a==="reset-state"){if(confirm("Reset AVERIS synthetic state in this browser?")){state=seedState();save();render();toast("State reset","Fresh synthetic dataset loaded.");}return}if(a==="export-state"){exportJson("averis-state.json",state);return}if(a==="export-audit"){exportJson("averis-audit.json",state.audit);return}if(a==="export-finance"){exportJson("averis-finance.json",state.finance);return}if(a==="export-insights"){exportJson("averis-analytics.json",{generatedAt:stamp(),version:VERSION,people:state.people,tasks:state.tasks,resources:state.resources,metrics:{open:state.tasks.filter(t=>t.status!=="Done").length,blocked:state.tasks.filter(t=>/blocked|overdue/i.test(t.status)).length}});return}if(a==="run-quality"){toast("Quality pass complete","Synthetic guardrails checked.");return}if(a==="refresh-view"){render();toast("View refreshed","Current local state re-rendered.");return}
if(a.startsWith("new-task-for:")){openModal("task");const p=findPerson(a.split(":")[1]);setTimeout(()=>{if(p)document.getElementById("f-task-person").value=p.name},20);return}
if(a.startsWith("edit-person:")){const p=findPerson(a.split(":")[1]);if(p)openModal("person",p);return}
if(a.startsWith("task-state:")){const t=state.tasks.find(x=>x.id===a.split(":")[1]);if(t){t.status={Open:"In progress","In progress":"Done",Blocked:"In progress",Overdue:"In progress"}[t.status]||"Done";audit("Advanced task",t.id);save();render();toast("Task updated",t.title+" → "+t.status)}return}
if(a.startsWith("reopen-task:")){const t=state.tasks.find(x=>x.id===a.split(":")[1]);if(t){t.status="Open";audit("Reopened task",t.id);save();render();toast("Task reopened",t.id)}return}
if(a.startsWith("move-appointment:")){const ap=state.appointments.find(x=>x.id===a.split(":")[1]);if(ap){const z=ap.time.split(":").map(Number),total=z[0]*60+z[1]+30;ap.time=String(Math.floor(total/60)%24).padStart(2,"0")+":"+String(total%60).padStart(2,"0");ap.state="Moved";audit("Moved appointment",ap.id);save();render();toast("Appointment moved",ap.id+" → "+ap.time)}return}
}

function bind(){
document.addEventListener("click",e=>{
const routeBtn=e.target.closest("[data-route]");if(routeBtn){navigate(routeBtn.dataset.route);return}
const close=e.target.closest("[data-close]");if(close){closeOverlay(close.dataset.close);return}
if(e.target.closest("#command-trigger")){openCommand();return}if(e.target.closest("#menu-button")){document.getElementById("sidebar").classList.add("open");document.getElementById("mobile-scrim").classList.add("show");return}if(e.target.closest("#sidebar-close")||e.target.id==="mobile-scrim"){document.getElementById("sidebar").classList.remove("open");document.getElementById("mobile-scrim").classList.remove("show");return}if(e.target.closest("#drawer-close")){closeDrawer();return}if(e.target.closest("#quick-add")){quickAdd();return}if(e.target.closest("#focus-button")){toggleFocus();return}if(e.target.closest("#notification-button")){navigate("messages");return}if(e.target.closest("#profile-button")){showDrawer("Profile",state.profile.name,'<div class="person-main">'+av(state.profile.name)+'<div class="person-id"><b style="font-size:13px">'+esc(state.profile.name)+'</b><small>'+esc(state.profile.role)+'</small></div></div><div class="drawer-section"><p>Local account: '+esc(state.account.email)+'</p></div>'+btn("go-settings","Open settings","primary") + '<button class="button danger" data-action="logout" type="button">Sign out</button>');return}
const p=e.target.closest("[data-open-person]");if(p){openPerson(p.dataset.openPerson);return}const t=e.target.closest("[data-open-task]");if(t){openTask(t.dataset.openTask);return}
const ap=e.target.closest("[data-open-appointment]");if(ap){const a=state.appointments.find(x=>x.id===ap.dataset.openAppointment);if(a)showDrawer("Appointment",a.id,'<div class="detail-grid"><div class="detail"><small>Time</small><b>'+a.time+'</b></div><div class="detail"><small>Person</small><b>'+a.person+'</b></div><div class="detail"><small>Resource</small><b>'+a.resource+'</b></div><div class="detail"><small>State</small><b>'+a.state+'</b></div></div>'+btn("move-appointment:"+a.id,"Move +30m","primary"));return}
const res=e.target.closest("[data-open-resource]");if(res){const r=state.resources.find(x=>x.id===res.dataset.openResource);if(r)showDrawer("Resource",r.name,'<div class="detail-grid"><div class="detail"><small>Type</small><b>'+r.type+'</b></div><div class="detail"><small>State</small><b>'+r.state+'</b></div><div class="detail"><small>Utilization</small><b>'+r.util+'%</b></div><div class="detail"><small>Owner</small><b>'+r.owner+'</b></div></div>');return}
const wf=e.target.closest("[data-open-workforce]");if(wf){const w=state.workforce.find(x=>x.id===wf.dataset.openWorkforce);if(w)showDrawer("Workforce",w.name,'<div class="detail-grid"><div class="detail"><small>Role</small><b>'+w.role+'</b></div><div class="detail"><small>State</small><b>'+w.state+'</b></div><div class="detail"><small>Load</small><b>'+w.load+'%</b></div></div>');return}
const dg=e.target.closest("[data-open-diagnostic]");if(dg){const d=state.diagnostics.find(x=>x.id===dg.dataset.openDiagnostic);if(d)showDrawer("Diagnostic workflow",d.id,'<div class="detail-grid"><div class="detail"><small>Person</small><b>'+d.person+'</b></div><div class="detail"><small>Workflow</small><b>'+d.type+'</b></div><div class="detail"><small>State</small><b>'+d.state+'</b></div><div class="detail"><small>Value</small><b>'+d.value+'</b></div></div>');return}
const ph=e.target.closest("[data-pharmacy]");if(ph){const p=state.pharmacy.find(x=>x.id===ph.dataset.pharmacy),v=prompt("New quantity",String(p.qty));if(v!==null&&!Number.isNaN(Number(v))){p.qty=Math.max(0,Number(v));audit("Adjusted inventory",p.id);save();render();toast("Inventory updated",p.item+" → "+p.qty+" "+p.unit)}return}
const fi=e.target.closest("[data-finance]");if(fi){const f=state.finance.find(x=>x.id===fi.dataset.finance);if(f)showDrawer("Finance",f.label,'<div class="detail-grid"><div class="detail"><small>Amount</small><b>'+f.amount+'</b></div><div class="detail"><small>State</small><b>'+f.state+'</b></div><div class="detail"><small>Date</small><b>'+f.date+'</b></div></div>');return}
const msg=e.target.closest("[data-message]");if(msg){const m=state.messages.find(x=>x.id===msg.dataset.message);if(m){m.read=true;save();showDrawer("Message",m.from,'<div class="drawer-section"><p>'+esc(m.text)+'</p></div><div class="drawer-section"><h3>Reply locally</h3><textarea class="textarea" id="reply-input" placeholder="Type a simulated reply"></textarea><div style="margin-top:8px">'+btn("reply:"+m.id,"Send reply","primary")+"</div></div>");updateChrome()}return}
const inc=e.target.closest("[data-incident]");if(inc){const i=state.incidents.find(x=>x.id===inc.dataset.incident);if(i)showDrawer("Incident",i.title,'<div class="detail-grid"><div class="detail"><small>Severity</small><b>'+i.severity+'</b></div><div class="detail"><small>State</small><b>'+i.state+'</b></div><div class="detail"><small>Person</small><b>'+i.person+'</b></div><div class="detail"><small>Owner</small><b>'+i.owner+'</b></div></div><div class="drawer-section"><p>'+esc(i.note)+'</p></div>'+btn("incident:"+i.id,"Advance lifecycle","primary"));return}
const sort=e.target.closest("[data-people-sort]");if(sort){peopleSort=sort.dataset.peopleSort;render();return}
const af=e.target.closest("[data-qfilter]");if(af){document.querySelectorAll("[data-qfilter]").forEach(x=>x.classList.remove("active"));af.classList.add("active");const m=af.dataset.qfilter;document.querySelectorAll("tbody tr").forEach(r=>{const s=r.textContent.toLowerCase();r.style.display=m==="all"?"":m==="critical"?(s.includes("critical")?"":"none"):m==="blocked"?(s.includes("blocked")?"":"none"):m==="open"?((s.includes("open")||s.includes("progress"))?"":"none"):""});return}
const ar=e.target.closest("[data-assistant]");if(ar){answerAssistant(ar.dataset.assistant);return}
const rp=e.target.closest("[data-report-preview]");if(rp){reportAction(rp.dataset.reportPreview,"preview");return}const rr=e.target.closest("[data-report-run]");if(rr){reportAction(rr.dataset.reportRun,"run");return}
const action=e.target.closest("[data-action]");if(action){handleAction(action.dataset.action);return}
const ci=e.target.closest("[data-command-index]");if(ci){openCommandItem(Number(ci.dataset.commandIndex));return}
});
document.addEventListener("input",e=>{if(e.target.id==="people-query"){peopleQuery=e.target.value;render()}if(e.target.id==="queue-query"){const q=e.target.value.toLowerCase();document.querySelectorAll("tbody tr").forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)?"":"none")}});
document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();openCommand();return}if(e.key==="Escape"){closeAll();return}if(!document.getElementById("command-overlay").hidden){if(e.key==="ArrowDown"){e.preventDefault();commandIndex=(commandIndex+1)%Math.max(commandItems.length,1);syncCommands()}if(e.key==="ArrowUp"){e.preventDefault();commandIndex=(commandIndex-1+commandItems.length)%Math.max(commandItems.length,1);syncCommands()}if(e.key==="Enter"){e.preventDefault();openCommandItem(commandIndex)}}});
document.getElementById("command-input")?.addEventListener("input",e=>buildCommands(e.target.value));
document.addEventListener("submit",e=>{const f=e.target.closest("[data-auth-form]");if(!f)return;e.preventDefault();authSubmit(f.dataset.authForm)});
}
function authSubmit(kind){if(kind==="login")loginNow();else if(kind==="register")registerNow()}
function updateChrome(){document.getElementById("crumb-current").textContent=ROUTES[route][0]}
function answerAssistant(kind){const out=document.getElementById("assistant-output");if(!out)return;let text="";if(kind==="attention")text="Escalated people: "+state.people.filter(p=>p.attention==="Escalated").map(p=>p.name).join(", ")+" . Blocked or overdue work: "+state.tasks.filter(t=>/blocked|overdue/i.test(t.status)).map(t=>t.title).join(", ")+".";else if(kind==="brief")text="Today has "+state.tasks.filter(t=>t.status!=="Done").length+" open tasks, "+state.appointments.length+" appointment slots, "+state.messages.filter(m=>!m.read).length+" unread messages, and "+state.incidents.filter(i=>i.state!=="Resolved").length+" active incidents.";else text="AVERIS stays synthetic and local: no real patient data, no clinical decisioning, no external AI calls, and no production integration.";out.innerHTML='<div class="card-head"><div><h3>Assistant output</h3><p>Local deterministic response</p></div><span class="status good">RULES</span></div><p style="font-size:10px;line-height:1.7">'+esc(text)+"</p>"}
function reportAction(id,mode){const r=state.reports.find(x=>x.id===id);if(!r)return;if(mode==="preview"){showDrawer("Report preview",r.name,'<div class="detail-grid"><div class="detail"><small>Type</small><b>'+r.type+'</b></div><div class="detail"><small>State</small><b>'+r.state+'</b></div><div class="detail"><small>People</small><b>'+state.people.length+'</b></div><div class="detail"><small>Tasks</small><b>'+state.tasks.length+'</b></div></div><p class="page-copy" style="margin-top:12px">Preview generated from current browser-local synthetic state.</p>');return}r.state="Ready";r.updated="just now";audit("Ran report",r.id);save();render();toast("Report generated",r.name)}
function extraActions(a){if(a.startsWith("reply:")){const m=state.messages.find(x=>x.id===a.split(":")[1]),input=document.getElementById("reply-input");if(m&&input&&input.value.trim()){m.reply=input.value.trim();audit("Sent reply",m.id);save();closeDrawer();toast("Reply sent","Thread updated locally.")}return}if(a.startsWith("incident:")){const i=state.incidents.find(x=>x.id===a.split(":")[1]);if(i){i.state={Open:"Investigating",Investigating:"Contained",Contained:"Resolved",Resolved:"Open"}[i.state]||"Open";audit("Advanced incident",i.id);save();closeDrawer();render();toast("Incident updated",i.state)}return}if(a.startsWith("move-appointment:")){handleAction(a);return}}
const originalHandle=handleAction;
handleAction=function(a){if(a.startsWith("reply:")||a.startsWith("incident:")){extraActions(a);return}originalHandle(a)};
function init(){bind();window.addEventListener("hashchange",()=>{const n=parseHash();if(n){route=n;render();document.getElementById("sidebar").classList.remove("open");document.getElementById("mobile-scrim").classList.remove("show")}});render();const clock=()=>{const n=new Date();document.getElementById("live-clock").textContent=n.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false});document.getElementById("live-date").textContent=n.toLocaleDateString([],{weekday:"short",day:"2-digit",month:"short",year:"numeric"})};clock();setInterval(clock,1000);navigator.serviceWorker?.register("./sw.js").catch(()=>{})}
return{init};
})();
document.addEventListener("DOMContentLoaded",AVERIS.init);